### PR TITLE
Add support for specifying subgroups that should default to being expanded

### PR DESCRIPTION
**Pull request by leebickmtu**
…anded.

@evanjd, one of the mentioned features.

### CODE REVIEW

**Comment by leebickmtu** [comment]
This is now ready for review.

**Comment by leebickmtu** [comment]
@evanjd I've been looking at this and I'm not quite sure how to fix it when in those modes. Might need some help on this one.

**Comment by e-kag** [comment]
@leebickmtu there has been a major version bump recently, and the `vertical-expanded` property has been replaced with a more versatile `vertical-opened-at` property. I'll get this PR in line with the new version and help with the issues @evanjd mentioned.

**Comment by evanjd** [comment]
Yep, that's why I said "the only thing left is tests". :) I might be pulled onto something else today so wanted to commit what I had in case you/others want to finish it.

Good point about the overflow case, I missed that.

**Comment by e-kag** [comment]
@evanjd I made a small change that gets overflow working, so all the requirements are met at the moment. Still, all that remains is tests at this point.

**Comment by e-kag** [comment]
@evanjd and @leebickmtu updated the tests to verify this behaviour in overflow, collapsed and vertical states.

**Pull request merged**
