### PR TITLE
Add vertical nav opening delay option.

### LINKED ISSUE #91: Support delay before opening/closing vertical nav on hover
Would like to see a configurable property for delay before the hover on vertical nav expands/closes the nav.

Less important but also nice would be property for transition duration for the vertical expand/close also.

### PR DESCRIPTION
**Pull request by leebickmtu**
Adding option to delay the opening of the vertical nav until the mouse has hovered for some time (implemented as 600ms). Fixes #91

### CODE REVIEW

**Comment by leebickmtu** [comment]
This PR is actually a bit out-of-date now. We have been maintaining changes needed for use in some projects on a separate fork. I'll try to update this tomorrow with rest of the changes for this feature.

There are several other features we added that I will try to make some other PRs for if you are going to be actively maintaining this again. We would like to not have to use a separate fork if that is the case.

**Comment by evanjd** [comment]
Thanks @leebickmtu, that'd be great.

> There are several other features we added that I will try to make some other PRs for if you are going to be actively maintaining this again. We would like to not have to use a separate fork if that is the case.

Please do. And yes, this is being actively maintained, you can expect reasonably prompt reviews in at least the short term.

**Comment by leebickmtu** [comment]
This is now ready for review.

**Comment by evanjd** [comment]
@leebickmtu 2.3.0 released with this change: https://github.com/predixdesignsystem/px-app-nav/releases/tag/v2.3.0

**Pull request merged**
